# Generated by Django 3.2.1 on 2021-05-08 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oznaceni_typu', models.CharField(help_text='Zadejte text o maximální délce 50 znaků; text musí být jedinečný', max_length=50, unique=True, verbose_name='Označení typu zboží')),
                ('oblast', models.CharField(blank=True, choices=[('supersport', 'Supersport'), ('naháč', 'Naháč'), ('cross', 'Cross'), ('skůtr', 'Skůtr'), ('cestovní', 'Cestovní'), ('ostatní', 'Ostatní')], default='Supersport', help_text='Vyberte označení oblasti', max_length=20, verbose_name='Oblast')),
            ],
            options={
                'verbose_name': 'Typ',
                'verbose_name_plural': 'Typy',
                'ordering': ['oznaceni_typu'],
            },
        ),
        migrations.CreateModel(
            name='Motorky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název motorky')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis motorky')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('stav', models.IntegerField(blank=True, choices=[(5, 'jako nová'), (4, 'málo používaná'), (3, 'často používaná'), (2, 'opotřebovaná'), (1, 'funkční vady')], default=3, help_text='Vyberte označení stavu', verbose_name='Stav zboží')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='motorky/%Y/%m/%d/', verbose_name='Fotka motorky')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motocykl.typ')),
            ],
            options={
                'verbose_name': 'Motorka',
                'verbose_name_plural': 'Motorky',
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
