# Generated by Django 3.2.1 on 2021-05-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocykl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorky',
            name='stav',
            field=models.IntegerField(blank=True, choices=[('jako nová', 5), ('málo používaná', 4), ('často používaná', 3), ('opotřebovaná', 2), ('funkční vady', 1)], default=3, help_text='Vyberte označení stavu', verbose_name='Stav zboží'),
        ),
        migrations.AlterField(
            model_name='typ',
            name='oblast',
            field=models.CharField(blank=True, choices=[('supersport', 'Supersport'), ('naháč', 'Naháč'), ('cross', 'Cross'), ('skútr', 'Skútr'), ('cestovní', 'Cestovní'), ('ostatní', 'Ostatní')], default='Supersport', help_text='Vyberte označení oblasti', max_length=20, verbose_name='Oblast'),
        ),
    ]
